//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simcode.PazCheck.CentralServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simcode.PazCheck.CentralServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon test finished. Errors: {0}. Warnings: {1}. Details in errors journal..
        /// </summary>
        public static string AddonTestFinished {
            get {
                return ResourceManager.GetString("AddonTestFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon test finished..
        /// </summary>
        public static string AddonTestFinished_Short {
            get {
                return ResourceManager.GetString("AddonTestFinished_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon test error.
        /// </summary>
        public static string AddonTestUnhandledException {
            get {
                return ResourceManager.GetString("AddonTestUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add journal analysis result to registry..
        /// </summary>
        public static string AddResultToPcObject_Event {
            get {
                return ResourceManager.GetString("AddResultToPcObject_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add journal analysis result to registry..
        /// </summary>
        public static string AddResultToPcObject_EventDesc {
            get {
                return ResourceManager.GetString("AddResultToPcObject_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API call access denied: {0} /{1}.
        /// </summary>
        public static string ApiCheckAccessFailed_Event {
            get {
                return ResourceManager.GetString("ApiCheckAccessFailed_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoloading.
        /// </summary>
        public static string Autoloading {
            get {
                return ResourceManager.GetString("Autoloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuator identifier mode.
        /// </summary>
        public static string BaseActuator_IdentifierMode_Option {
            get {
                return ResourceManager.GetString("BaseActuator_IdentifierMode_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices analysis. Date range, begin: {0}, end: {1}.
        /// </summary>
        public static string CalculateResults_Event {
            get {
                return ResourceManager.GetString("CalculateResults_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log events analysis.
        /// </summary>
        public static string CalculateResults_JobTitle {
            get {
                return ResourceManager.GetString("CalculateResults_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE Matrix identifier mode.
        /// </summary>
        public static string CeMatrix_IdentifierMode_Option {
            get {
                return ResourceManager.GetString("CeMatrix_IdentifierMode_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear unversioned changes in project {0}.
        /// </summary>
        public static string ClearUnversionedChanges_EventDesc {
            get {
                return ResourceManager.GetString("ClearUnversionedChanges_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear unversioned changes in project.
        /// </summary>
        public static string ClearUnversionedChanges_EventName {
            get {
                return ResourceManager.GetString("ClearUnversionedChanges_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Started.
        /// </summary>
        public static string ComponentStarted_Event {
            get {
                return ResourceManager.GetString("ComponentStarted_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Started: {0}.
        /// </summary>
        public static string ComponentStarted_EventDesc {
            get {
                return ResourceManager.GetString("ComponentStarted_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component started with SuperUser role enabled..
        /// </summary>
        public static string ComponentStartedWithSuperUser_Event {
            get {
                return ResourceManager.GetString("ComponentStartedWithSuperUser_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component started with SuperUser role enabled: {0}.
        /// </summary>
        public static string ComponentStartedWithSuperUser_EventDesc {
            get {
                return ResourceManager.GetString("ComponentStartedWithSuperUser_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Stopped.
        /// </summary>
        public static string ComponentStopped_Event {
            get {
                return ResourceManager.GetString("ComponentStopped_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Stopped: {0}.
        /// </summary>
        public static string ComponentStopped_EventDesc {
            get {
                return ResourceManager.GetString("ComponentStopped_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept any server certificate (dangerous).
        /// </summary>
        public static string DangerousAcceptAnyServerCertificate_Option {
            get {
                return ResourceManager.GetString("DangerousAcceptAnyServerCertificate_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Info (only added for test mode):.
        /// </summary>
        public static string DebugInfoHeader {
            get {
                return ResourceManager.GetString("DebugInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue press OK button.
        /// </summary>
        public static string Default_AddonTestInfo {
            get {
                return ResourceManager.GetString("Default_AddonTestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnost Module.
        /// </summary>
        public static string DiagnostAddon_Desc {
            get {
                return ResourceManager.GetString("DiagnostAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic journal events analysis started.
        /// </summary>
        public static string DiagnostCalculation_AutoBegin_Event {
            get {
                return ResourceManager.GetString("DiagnostCalculation_AutoBegin_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic journal events analysis started. Project: {0}; Begin Time: {1}; End Time {2}..
        /// </summary>
        public static string DiagnostCalculation_AutoBegin_EventDesc {
            get {
                return ResourceManager.GetString("DiagnostCalculation_AutoBegin_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal events analysis.
        /// </summary>
        public static string DiagnostCalculation_Event {
            get {
                return ResourceManager.GetString("DiagnostCalculation_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal events analysis. Project: {0}; Begin Time: {1}; End Time {2}..
        /// </summary>
        public static string DiagnostCalculation_EventDesc {
            get {
                return ResourceManager.GetString("DiagnostCalculation_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail sending..
        /// </summary>
        public static string EMails_Sending_Event {
            get {
                return ResourceManager.GetString("EMails_Sending_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid e-mail address for test message. Last report from Diagnost will be sent..
        /// </summary>
        public static string EMailsAddon_AddonTestInfo {
            get {
                return ResourceManager.GetString("EMailsAddon_AddonTestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mails Module.
        /// </summary>
        public static string EMailsAddon_Desc {
            get {
                return ResourceManager.GetString("EMailsAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Sender Address.
        /// </summary>
        public static string EMailsAddon_EMailFrom_Address_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_EMailFrom_Address_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Sender Name.
        /// </summary>
        public static string EMailsAddon_EMailFrom_Name_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_EMailFrom_Name_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Host.
        /// </summary>
        public static string EMailsAddon_SmtpHost_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_SmtpHost_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Host connection additional params.
        /// </summary>
        public static string EMailsAddon_SmtpParams_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_SmtpParams_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Host Password.
        /// </summary>
        public static string EMailsAddon_SmtpPassword_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_SmtpPassword_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Port.
        /// </summary>
        public static string EMailsAddon_SmtpPort_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_SmtpPort_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Host User Name.
        /// </summary>
        public static string EMailsAddon_SmtpUserName_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_SmtpUserName_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PazCheck URL for reference in mail.
        /// </summary>
        public static string EMailsAddon_Url_Option {
            get {
                return ResourceManager.GetString("EMailsAddon_Url_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity deleted: {0}.
        /// </summary>
        public static string EntityDeleted_Event {
            get {
                return ResourceManager.GetString("EntityDeleted_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity updated: {0}; Details: &quot;{1}&quot;.
        /// </summary>
        public static string EntityPatched_Event {
            get {
                return ResourceManager.GetString("EntityPatched_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity posted: {0}; Details: &quot;{1}&quot;.
        /// </summary>
        public static string EntityPosted_Event {
            get {
                return ResourceManager.GetString("EntityPosted_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(UnitIdentifier): invalid unit identifier.
        /// </summary>
        public static string Error_InvalidUnitIdentifier {
            get {
                return ResourceManager.GetString("Error_InvalidUnitIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export events to file..
        /// </summary>
        public static string ExportEventsToFile_Event {
            get {
                return ResourceManager.GetString("ExportEventsToFile_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export events to file. Event type: {0}.
        /// </summary>
        public static string ExportEventsToFile_EventDesc {
            get {
                return ResourceManager.GetString("ExportEventsToFile_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export version comparison result to file..
        /// </summary>
        public static string ExportVersionComparisonToFile_Event {
            get {
                return ResourceManager.GetString("ExportVersionComparisonToFile_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export version comparison result to file. Object: {0}; Version 1: {1}; Version 2: {2}..
        /// </summary>
        public static string ExportVersionComparisonToFile_EventDesc {
            get {
                return ResourceManager.GetString("ExportVersionComparisonToFile_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server cannot read file .
        /// </summary>
        public static string FileReadingError {
            get {
                return ResourceManager.GetString("FileReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Base Actuator File.
        /// </summary>
        public static string ImportBaseActuatorFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportBaseActuatorFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CE Matrix File.
        /// </summary>
        public static string ImportCeMatrixFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportCeMatrixFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Events Journal File.
        /// </summary>
        public static string ImportEventsJournalFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportEventsJournalFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import License File.
        /// </summary>
        public static string ImportLicenseFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportLicenseFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Project File.
        /// </summary>
        public static string ImportProjectFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportProjectFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Safety Controller File.
        /// </summary>
        public static string ImportSafetyControllerFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportSafetyControllerFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tag File.
        /// </summary>
        public static string ImportTagFile_JobTitle {
            get {
                return ResourceManager.GetString("ImportTagFile_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        public static string Instructor_RoleName {
            get {
                return ResourceManager.GetString("Instructor_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test E-Mail is not set..
        /// </summary>
        public static string InvalidTestOptionsValue_Empty {
            get {
                return ResourceManager.GetString("InvalidTestOptionsValue_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend identifiers mode.
        /// </summary>
        public static string Legend_IdentifierMode_Option {
            get {
                return ResourceManager.GetString("Legend_IdentifierMode_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Module.
        /// </summary>
        public static string MonitoringAddon_Desc {
            get {
                return ResourceManager.GetString("MonitoringAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter new password:.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mails .
        /// </summary>
        public static string NotifyUsers_Event {
            get {
                return ResourceManager.GetString("NotifyUsers_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mails.
        /// </summary>
        public static string NotifyUsers_EventDesc {
            get {
                return ResourceManager.GetString("NotifyUsers_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base module.
        /// </summary>
        public static string PazCheckCentralServerAddon_Desc {
            get {
                return ResourceManager.GetString("PazCheckCentralServerAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic process event logs processing.
        /// </summary>
        public static string ProcessEventMessages_JobTitle {
            get {
                return ResourceManager.GetString("ProcessEventMessages_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, cofirm password:.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring objects identifiers mode.
        /// </summary>
        public static string SafetyController_IdentifierMode_Option {
            get {
                return ResourceManager.GetString("SafetyController_IdentifierMode_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved unversioned changes.
        /// </summary>
        public static string SaveUnversionedChanges_Event {
            get {
                return ResourceManager.GetString("SaveUnversionedChanges_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving project version. Project: {0}; Comment: {1}.
        /// </summary>
        public static string SaveUnversionedChanges_EventDesc {
            get {
                return ResourceManager.GetString("SaveUnversionedChanges_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving project version.
        /// </summary>
        public static string SaveUnversionedChanges_EventName {
            get {
                return ResourceManager.GetString("SaveUnversionedChanges_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier, Title, Desc.
        /// </summary>
        public static string SearchBy_IdentifierTitleDesc {
            get {
                return ResourceManager.GetString("SearchBy_IdentifierTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Only.
        /// </summary>
        public static string StandardFilterName_Templates {
            get {
                return ResourceManager.GetString("StandardFilterName_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor approve new active project version. Project: {0}; new active project version: {1} - {2}.
        /// </summary>
        public static string SupervisorApproveActiveProjectVersion_EventDesc {
            get {
                return ResourceManager.GetString("SupervisorApproveActiveProjectVersion_EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name mode.
        /// </summary>
        public static string Tag_IdentifierMode_Option {
            get {
                return ResourceManager.GetString("Tag_IdentifierMode_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test E-Mail.
        /// </summary>
        public static string TestEMailSubject {
            get {
                return ResourceManager.GetString("TestEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program critical error..
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitEvents Max Records Count.
        /// </summary>
        public static string UnitEvents_MaxRecordsCount_Option {
            get {
                return ResourceManager.GetString("UnitEvents_MaxRecordsCount_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitEvents Max Storage Time.
        /// </summary>
        public static string UnitEvents_MaxStorageTime_Option {
            get {
                return ResourceManager.GetString("UnitEvents_MaxStorageTime_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum period of time to recieve new unit events..
        /// </summary>
        public static string UnitEvents_MaxUpdatePeriod_Option {
            get {
                return ResourceManager.GetString("UnitEvents_MaxUpdatePeriod_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitEvents Warning Records Count.
        /// </summary>
        public static string UnitEvents_WarningRecordsCount_Option {
            get {
                return ResourceManager.GetString("UnitEvents_WarningRecordsCount_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Identifier.
        /// </summary>
        public static string UnitIdentifier_Option {
            get {
                return ResourceManager.GetString("UnitIdentifier_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Module objects update period.
        /// </summary>
        public static string UpdatePeriod_Option {
            get {
                return ResourceManager.GetString("UpdatePeriod_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out User.
        /// </summary>
        public static string UserLogOut_Event {
            get {
                return ResourceManager.GetString("UserLogOut_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logout due to exceeding maximum operating time.
        /// </summary>
        public static string UserLogOut_Event_Desc_RefreshTokenTimeout {
            get {
                return ResourceManager.GetString("UserLogOut_Event_Desc_RefreshTokenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logout due to inactivity timeout.
        /// </summary>
        public static string UserLogOut_Event_Desc_Timeout {
            get {
                return ResourceManager.GetString("UserLogOut_Event_Desc_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logout by button.
        /// </summary>
        public static string UserLogOut_Event_Desc_UserAction {
            get {
                return ResourceManager.GetString("UserLogOut_Event_Desc_UserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write сonfiguration file.
        /// </summary>
        public static string WriteConfigurationFile_Event {
            get {
                return ResourceManager.GetString("WriteConfigurationFile_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write сonfiguration file: {0} {1}.
        /// </summary>
        public static string WriteConfigurationFile_EventDesc {
            get {
                return ResourceManager.GetString("WriteConfigurationFile_EventDesc", resourceCulture);
            }
        }
    }
}
