




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace Simcode.PazCheck.CentralServer.Common.Properties
{ 
    public class ResourceStrings
    {
        
public const String EmptyBaseActuator_Title = @"EmptyBaseActuator_Title";
        
public const String Error_ActuatorOrBaseActuatorParamNotFoundInDb = @"Error_ActuatorOrBaseActuatorParamNotFoundInDb";
        
public const String Error_MultipleActuatorParamsFoundInDb = @"Error_MultipleActuatorParamsFoundInDb";
        
public const String Error_MultipleBaseActuatorParamsFoundInDb = @"Error_MultipleBaseActuatorParamsFoundInDb";
        
public const String Error_MultipleMathOperators = @"Error_MultipleMathOperators";
        
public const String Error_MultipleTagsFoundInDb = @"Error_MultipleTagsFoundInDb";
        
public const String Error_TagConditionNotFoundInDb = @"Error_TagConditionNotFoundInDb";
        
public const String Error_TagNotFoundInDb = @"Error_TagNotFoundInDb";
        
public const String UnknownFileFormatVersion = @"UnknownFileFormatVersion";
        
public const String ImportBaseActuators_ProgressLabel = @"ImportBaseActuators_ProgressLabel";
        
public const String ImportCeMatrices_ProgressLabel = @"ImportCeMatrices_ProgressLabel";
        
public const String ImportFile_EventName = @"ImportFile_EventName";
        
public const String ImportSerializationRootObject_Error = @"ImportSerializationRootObject_Error";
        
public const String ImportSerializationRootObject_Error_DbFileReferenceNoFile = @"ImportSerializationRootObject_Error_DbFileReferenceNoFile";
        
public const String ImportSerializationRootObject_Error_NoBaseActuator = @"ImportSerializationRootObject_Error_NoBaseActuator";
        
public const String Error_ImportSerializationRootObject_BaseActuatorWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_BaseActuatorWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_CeMatrixWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_CeMatrixWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_DbFileReferenceWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_DbFileReferenceWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_ParamWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_ParamWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_SafetyControllerWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_SafetyControllerWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_TagConditionWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_TagConditionWithUnversionedChangesExists";
        
public const String Error_ImportSerializationRootObject_TagWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_TagWithUnversionedChangesExists";
        
public const String ImportSafetyControllers_ProgressLabel = @"ImportSafetyControllers_ProgressLabel";
        
public const String ImportTags_ProgressLabel = @"ImportTags_ProgressLabel";
        
public const String Information_AddedTagCondition = @"Information_AddedTagCondition";
        
public const String InvalidFileInPcArchive = @"InvalidFileInPcArchive";
        
public const String InvalidFileFormat = @"InvalidFileFormat";
        
public const String InformationSecurityEvents_MaxRecordsCount_Option = @"InformationSecurityEvents_MaxRecordsCount_Option";
        
public const String InformationSecurityEvents_MaxStorageTime_Option = @"InformationSecurityEvents_MaxStorageTime_Option";
        
public const String InformationSecurityEvents_WarningRecordsCount_Option = @"InformationSecurityEvents_WarningRecordsCount_Option";
        
public const String LoggingAddon_Desc = @"LoggingAddon_Desc";
        
public const String UserEvents_MaxRecordsCount_Option = @"UserEvents_MaxRecordsCount_Option";
        
public const String UserEvents_MaxStorageTime_Option = @"UserEvents_MaxStorageTime_Option";
        
public const String UserEvents_WarningRecordsCount_Option = @"UserEvents_WarningRecordsCount_Option";
        
public const String InvalidAddonIdentifier = @"InvalidAddonIdentifier";
        
public const String CsvObjectsFile_InvalidObjectProperty = @"CsvObjectsFile_InvalidObjectProperty";
        
public const String CsvObjectsFile_UnknownCollection = @"CsvObjectsFile_UnknownCollection";
        
public const String FileReferenceError = @"FileReferenceError";
        
public const String InvalidJournalParamData = @"InvalidJournalParamData";
        
public const String IdentifierDoesNotExist = @"IdentifierDoesNotExist";
        
public const String DuplicatedIdentifier = @"DuplicatedIdentifier";
        
public const String InvalidAddonType = @"InvalidAddonType";
        
public const String Deserialization_Error = @"Deserialization_Error";
        
public const String UnitTitleScope = @"UnitTitleScope";
        
public const String DbInitializationSuccess = @"DbInitializationSuccess";
        
public const String DbUpdateSuccess = @"DbUpdateSuccess";
        
public const String Error_FileInvalidFormat = @"Error_FileInvalidFormat";
        
public const String PasswordSuccesfullyChanged = @"PasswordSuccesfullyChanged";
        
public const String Error_ImportSerializationRootObject_LegendWithUnversionedChangesExists = @"Error_ImportSerializationRootObject_LegendWithUnversionedChangesExists";
        
public const String WorksheetScopeName = @"WorksheetScopeName";
        
public const String Error_MultipleTagConditionsFoundInDb = @"Error_MultipleTagConditionsFoundInDb";
        
public const String ColumnScope = @"ColumnScope";
        
public const String RowScope = @"RowScope";
        
public const String QuickTestSuccess = @"QuickTestSuccess";
        
public const String Error_AeNotMapped = @"Error_AeNotMapped";
        
public const String Error_TagConditionSymbolToDisplayAlreadySet = @"Error_TagConditionSymbolToDisplayAlreadySet";
        
public const String Error_DuplicateTagCondition = @"Error_DuplicateTagCondition";
        
public const String ObjectSystem = @"ObjectSystem";
        
public const String CryptoEntity = @"CryptoEntity";
        
public const String EntityAdded_EventName = @"EntityAdded_EventName";
        
public const String EntityDeleted_EventName = @"EntityDeleted_EventName";
        
public const String LicenseFile = @"LicenseFile";
        
public const String Project = @"Project";
        
public const String Unit = @"Unit";
        
public const String CeMatrices = @"CeMatrices";
        
public const String EventsJournal_ContentType = @"EventsJournal_ContentType";
        
public const String ExcelFile_ContentType = @"ExcelFile_ContentType";
        
public const String ImportFile_EventDesc = @"ImportFile_EventDesc";
        
public const String LicenseFile_ContentType = @"LicenseFile_ContentType";
        
public const String Tags = @"Tags";
        
public const String Unknown_ContentType = @"Unknown_ContentType";
        
public const String ZipArchive_ContentType = @"ZipArchive_ContentType";
        
public const String RoleBusinessFunction = @"RoleBusinessFunction";
        
public const String Role = @"Role";
        
public const String IsAllowed = @"IsAllowed";
        
public const String IsDisallowed = @"IsDisallowed";
        
public const String RoleAttributesChanged_EventDesc = @"RoleAttributesChanged_EventDesc";
        
public const String RoleAttributesChanged_EventName = @"RoleAttributesChanged_EventName";
        
public const String RolePermission = @"RolePermission";
        
public const String ComponentStartStop_EventId = @"ComponentStartStop_EventId";
        
public const String Calculation_EventId = @"Calculation_EventId";
        
public const String Connection_EventId = @"Connection_EventId";
        
public const String DataExported_EventId = @"DataExported_EventId";
        
public const String DataImported_EventId = @"DataImported_EventId";
        
public const String EntityChanged_EventId = @"EntityChanged_EventId";
        
public const String RefreshTokenGenerated_EventId = @"RefreshTokenGenerated_EventId";
        
public const String RoleAttributesChanged_EventId = @"RoleAttributesChanged_EventId";
        
public const String RolesChanged_EventId = @"RolesChanged_EventId";
        
public const String UserLogIn_EventId = @"UserLogIn_EventId";
        
public const String UserLogOut_EventId = @"UserLogOut_EventId";
        
public const String Access_EventId = @"Access_EventId";
        
public const String Unknown_Severity = @"Unknown_Severity";
        
public const String ParamDesc_CeMatrixSource = @"ParamDesc_CeMatrixSource";
        
public const String ParamDesc_TagSource = @"ParamDesc_TagSource";
        
public const String ParamDesc_ProjectVersionSource = @"ParamDesc_ProjectVersionSource";
        
public const String ParamDesc_MaxActuationTimeClose = @"ParamDesc_MaxActuationTimeClose";
        
public const String SupervisorApproval_EventId = @"SupervisorApproval_EventId";
        
public const String SupervisorApproveActiveProjectVersion_Event = @"SupervisorApproveActiveProjectVersion_Event";
        
public const String BaseActuatorType_Pump = @"BaseActuatorType_Pump";
        
public const String BaseActuatorType_Valve = @"BaseActuatorType_Valve";
        
public const String BasePcObjectType_Area = @"BasePcObjectType_Area";
        
public const String BasePcObjectType_Tag = @"BasePcObjectType_Tag";
        
public const String BasePcObjectType_Unit = @"BasePcObjectType_Unit";
        
public const String PcEntityType_Main = @"PcEntityType_Main";
        
public const String PcObjectEventTypeTitle_ActuatorAction = @"PcObjectEventTypeTitle_ActuatorAction";
        
public const String Error_MultiplePcObjectsFoundInDb = @"Error_MultiplePcObjectsFoundInDb";
        
public const String Error_PcObjectNotFoundInDb = @"Error_PcObjectNotFoundInDb";
        
public const String ParamValue_FaultTriggered = @"ParamValue_FaultTriggered";
        
public const String ParamValue_LateTriggered = @"ParamValue_LateTriggered";
        
public const String ParamValue_NotTriggered = @"ParamValue_NotTriggered";
        
public const String ParamValue_SuccessFirstTriggered = @"ParamValue_SuccessFirstTriggered";
        
public const String ParamValue_SuccessTriggered = @"ParamValue_SuccessTriggered";
        
public const String SearchBy_All = @"SearchBy_All";
        
public const String ParamDesc_MaxActuationTimeOpen = @"ParamDesc_MaxActuationTimeOpen";
        
public const String Error_AeNotMapped_IncorrectMappingExpression = @"Error_AeNotMapped_IncorrectMappingExpression";
        
public const String ConfigurationChange_EventId = @"ConfigurationChange_EventId";
        
public const String Connected_Event = @"Connected_Event";
        
public const String Connected_EventDesc = @"Connected_EventDesc";
        
public const String Disconnected_Event = @"Disconnected_Event";
        
public const String Disconnected_EventDesc = @"Disconnected_EventDesc";
        
public const String CellScope = @"CellScope";
        
public const String ParamDesc_CommandActuationTime = @"ParamDesc_CommandActuationTime";
        
public const String ParamDesc_LogicActuationTime = @"ParamDesc_LogicActuationTime";
        
public const String BaseActuator = @"BaseActuator";
        
public const String CeMatrix = @"CeMatrix";
        
public const String SafetyController = @"SafetyController";
        
public const String Tag = @"Tag";
        
public const String ActuatorParam = @"ActuatorParam";
        
public const String BaseActuatorParam = @"BaseActuatorParam";
        
public const String Cell = @"Cell";
        
public const String CeMatrixComment = @"CeMatrixComment";
        
public const String CeMatrixParam = @"CeMatrixParam";
        
public const String Column = @"Column";
        
public const String DbFileReference = @"DbFileReference";
        
public const String Row = @"Row";
        
public const String SafetyControllerParam = @"SafetyControllerParam";
        
public const String TagCondition = @"TagCondition";
        
public const String TagParam = @"TagParam";
        
public const String Undefined = @"Undefined";
        
public const String Result = @"Result";
        
public const String PcObjectEventTypeTitle_EmergencyShutdown = @"PcObjectEventTypeTitle_EmergencyShutdown";
        
public const String ParamDesc_EmergencyShutdownLevel = @"ParamDesc_EmergencyShutdownLevel";
        
public const String CriterionDesc_From = @"CriterionDesc_From";
        
public const String CriterionDesc_To = @"CriterionDesc_To";
        
public const String PcObjectEventTypeTitle_ManualCheck = @"PcObjectEventTypeTitle_ManualCheck";
        
public const String CriterionDesc_EventType = @"CriterionDesc_EventType";
        
public const String CriterionDesc_BasePcObject_Identifier = @"CriterionDesc_BasePcObject_Identifier";
        
public const String ParamDesc_Strict_PrimeCause_TagName = @"ParamDesc_Strict_PrimeCause_TagName";
        
public const String SearchBy_EventDesc = @"SearchBy_EventDesc";
        
public const String ParamDesc_PossibleResultSources = @"ParamDesc_PossibleResultSources";
        
public const String ExportResultToFile_Event = @"ExportResultToFile_Event";
        
public const String ExportResultToFile_EventDesc = @"ExportResultToFile_EventDesc";
        
public const String ParamDesc_CommandActuationType = @"ParamDesc_CommandActuationType";
        
public const String ParamDesc_LogicActuationType = @"ParamDesc_LogicActuationType";
        
public const String EntityModified_EventName = @"EntityModified_EventName";
        
public const String Desc = @"Desc";
        
public const String Title = @"Title";
        
public const String ParamDesc_FaultTriggered = @"ParamDesc_FaultTriggered";
        
public const String ParamDesc_LateTriggered = @"ParamDesc_LateTriggered";
        
public const String ParamDesc_NotActivated = @"ParamDesc_NotActivated";
        
public const String ParamDesc_NotTriggered = @"ParamDesc_NotTriggered";
        
public const String ParamDesc_SuccessFirstTriggered = @"ParamDesc_SuccessFirstTriggered";
        
public const String ParamDesc_SuccessTriggered = @"ParamDesc_SuccessTriggered";
        
public const String ParamDesc_ResultEventDesc = @"ParamDesc_ResultEventDesc";
        
public const String ParamDesc_ResultEventTagName = @"ParamDesc_ResultEventTagName";
        
public const String ParamDesc_ResultEventTime = @"ParamDesc_ResultEventTime";
        
public const String High_Severity = @"High_Severity";
        
public const String Low_Severity = @"Low_Severity";
        
public const String Medium_Severity = @"Medium_Severity";
        
public const String VeryHigh_Severity = @"VeryHigh_Severity";
        
public const String BasePcObject = @"BasePcObject";
        
public const String PcObject = @"PcObject";
        
public const String PcObjectEvent = @"PcObjectEvent";
        
public const String PcObject_Parent = @"PcObject_Parent";
        
public const String BasePcObjectType = @"BasePcObjectType";
        
public const String Added = @"Added";
        
public const String BaseActuators = @"BaseActuators";
        
public const String BasePcObjects = @"BasePcObjects";
        
public const String PcObjects = @"PcObjects";
        
public const String SafetyControllers = @"SafetyControllers";
        
public const String Updated = @"Updated";
        
public const String Deleted = @"Deleted";
        
public const String IdentifierDuplicated = @"IdentifierDuplicated";
        
public const String Legend = @"Legend";
        
public const String PcObjectParentLoop = @"PcObjectParentLoop";
        
public const String SearchBy_TagDesc = @"SearchBy_TagDesc";
        
public const String SearchBy_TagName = @"SearchBy_TagName";
        
public const String PcObjectEventType = @"PcObjectEventType";
        
public const String ResultReference = @"ResultReference";
        
public const String JournalParamValuesFile_InvalidLine = @"JournalParamValuesFile_InvalidLine";
        
public const String LineScope = @"LineScope";
        
public const String IdentifierIsNull = @"IdentifierIsNull";
        
public const String EntitiesDeleted_EventDesc = @"EntitiesDeleted_EventDesc";
        
public const String EntitiesDeleted_EventName = @"EntitiesDeleted_EventName";
        
public const String TemplateTagsLooped = @"TemplateTagsLooped";
        
public const String Error_MultipleParamsFoundInDb = @"Error_MultipleParamsFoundInDb";
        
public const String ParamDesc_TagTemplate = @"ParamDesc_TagTemplate";
        
public const String CsvObjectsFile_InvalidObjectValue = @"CsvObjectsFile_InvalidObjectValue";
        
public const String InvalidAddonOptionValue_Empty = @"InvalidAddonOptionValue_Empty";
        
public const String ImportRemoteFile_EventName = @"ImportRemoteFile_EventName";
        
public const String ImportRemoteFile_EventDesc = @"ImportRemoteFile_EventDesc";
        
public const String ParamDesc_EventStatus = @"ParamDesc_EventStatus";
        
public const String EventStatus_Finished = @"EventStatus_Finished";
        
public const String EventStatus_NotFinished = @"EventStatus_NotFinished";
        
public const String PcObjectEventTypeTitle_DBK = @"PcObjectEventTypeTitle_DBK";
        
public const String PcObjectEventTypeTitle_ForcedVariable = @"PcObjectEventTypeTitle_ForcedVariable";
        
public const String SafetyIndex_Red = @"SafetyIndex_Red";
        
public const String SafetyIndex_Green = @"SafetyIndex_Green";
        
public const String SafetyIndex_Unknown = @"SafetyIndex_Unknown";
        
public const String SafetyIndex_Yellow = @"SafetyIndex_Yellow";
        
public const String ParamDesc_SafetyIndex = @"ParamDesc_SafetyIndex";
        
public const String ParamDesc_MalfunctionCategory = @"ParamDesc_MalfunctionCategory";
        
public const String ParamDesc_AlarmIntensity = @"ParamDesc_AlarmIntensity";
        
public const String ParamDesc = @"ParamDesc";
        
public const String ProjectVersionType = @"ProjectVersionType";
        
public const String ParamDesc_SafetyControllerTemplate = @"ParamDesc_SafetyControllerTemplate";
        
public const String InvalidDateTimeString = @"InvalidDateTimeString";
        
public const String Activator_CreateInstance_Error = @"Activator_CreateInstance_Error";
        
public const String Error_TemplateFileDoesNotExist = @"Error_TemplateFileDoesNotExist";
        
public const String ParamDesc_Strict_PrimeCause_Condition = @"ParamDesc_Strict_PrimeCause_Condition";
        
public const String ParamDesc_Strict_PrimeCause_Time = @"ParamDesc_Strict_PrimeCause_Time";
        
public const String SearchBy_PrimeCause = @"SearchBy_PrimeCause";
        
public const String Scope_FileName = @"Scope_FileName";
        
public const String InvalidAddonOptionValue = @"InvalidAddonOptionValue";
        
public const String Scope_AddonOption = @"Scope_AddonOption";
        
public const String ParamDesc_Desc = @"ParamDesc_Desc";
        
public const String ParamDesc_NewState = @"ParamDesc_NewState";
        
public const String ParamDesc_OldState = @"ParamDesc_OldState";
        
public const String SeeUserEventsLog = @"SeeUserEventsLog";
        
public const String AddonTest_EventId = @"AddonTest_EventId";
        
public const String AddonTest_EventDesc = @"AddonTest_EventDesc";
        
public const String SearchBy_ExcludeContent = @"SearchBy_ExcludeContent";
        
public const String InvalidSymbolToDisplay = @"InvalidSymbolToDisplay";
        
public const String Scope_TagCondition = @"Scope_TagCondition";
        
public const String Scope_TagName = @"Scope_TagName";
        
public const String ParamDesc_SafetyIndexDescGreen = @"ParamDesc_SafetyIndexDescGreen";
        
public const String ParamDesc_SafetyIndexDescRed = @"ParamDesc_SafetyIndexDescRed";
        
public const String ParamDesc_SafetyIndexDescYellow = @"ParamDesc_SafetyIndexDescYellow";
        
public const String SafetyIndexDesc_NoData = @"SafetyIndexDesc_NoData";
        
public const String ParamDesc_BaseActuator = @"ParamDesc_BaseActuator";
        
public const String ParamDesc_Title = @"ParamDesc_Title";
        
public const String ParamDesc_Comment = @"ParamDesc_Comment";
        
public const String ParamDesc_Manufacturer = @"ParamDesc_Manufacturer";
        
public const String BasePcObject_SystemArea_Title = @"BasePcObject_SystemArea_Title";
        
public const String BasePcObject_SystemItem_Title = @"BasePcObject_SystemItem_Title";
        
public const String PcObject_SystemArea_Title = @"PcObject_SystemArea_Title";
        
public const String DataImportError_EventId = @"DataImportError_EventId";
        
public const String RemoteFileIsNotImported_EventDesc = @"RemoteFileIsNotImported_EventDesc";
        
public const String RemoteFileIsNotImported_EventName = @"RemoteFileIsNotImported_EventName";
        
public const String InformationSecurityEvents_WarningRecordsCount_EventDesc = @"InformationSecurityEvents_WarningRecordsCount_EventDesc";
        
public const String InformationSecurityEvents_WarningRecordsCount_EventName = @"InformationSecurityEvents_WarningRecordsCount_EventName";
        
public const String UnitEvents_WarningRecordsCount_EventDesc = @"UnitEvents_WarningRecordsCount_EventDesc";
        
public const String UnitEvents_WarningRecordsCount_EventName = @"UnitEvents_WarningRecordsCount_EventName";
        
public const String UserEvents_WarningRecordsCount_EventDesc = @"UserEvents_WarningRecordsCount_EventDesc";
        
public const String UserEvents_WarningRecordsCount_EventName = @"UserEvents_WarningRecordsCount_EventName";
        
public const String WarningRecordsCount_EventId = @"WarningRecordsCount_EventId";
        
public const String Legends = @"Legends";
        
public const String Succeeded_False = @"Succeeded_False";
        
public const String Succeeded_True = @"Succeeded_True";
        
public const String DestinationTypeDesc_HumanReadable_ExcelFile = @"DestinationTypeDesc_HumanReadable_ExcelFile";
        
public const String SearchBy_ExcludeContent_UnitEventsInterval = @"SearchBy_ExcludeContent_UnitEventsInterval";
        
public const String ParamDesc_TrendDeadbandPercentage = @"ParamDesc_TrendDeadbandPercentage";
        
public const String ParamDesc_TrendEnabled = @"ParamDesc_TrendEnabled";
        
public const String ParamDesc_TrendPeriod = @"ParamDesc_TrendPeriod";
        
public const String ParamDesc_TrendEU_DA = @"ParamDesc_TrendEU_DA";
        
public const String ParamDesc_TrendMax_DA = @"ParamDesc_TrendMax_DA";
        
public const String ParamDesc_TrendMin_DA = @"ParamDesc_TrendMin_DA";
        
public const String ParamDesc_TrendStorePeriod = @"ParamDesc_TrendStorePeriod";
        
public const String BasePcObject_Overview_Title = @"BasePcObject_Overview_Title";
        
public const String BasePcObject_OtherArea_Title = @"BasePcObject_OtherArea_Title";
        
public const String BasePcObject_OtherItem_Title = @"BasePcObject_OtherItem_Title";
        
public const String PcObject_OtherArea_Title = @"PcObject_OtherArea_Title";
        
public const String InvalidDaCondition = @"InvalidDaCondition";
        
public const String ParamDesc_TrendBeginTimeUtc = @"ParamDesc_TrendBeginTimeUtc";
        
public const String ParamDesc_TrendEndTimeUtc = @"ParamDesc_TrendEndTimeUtc";
        
public const String BasePcObject_Default_Title = @"BasePcObject_Default_Title";
        
public const String SearchBy_PcObjectEventAll = @"SearchBy_PcObjectEventAll";
        
public const String ParamDesc_ActuationType = @"ParamDesc_ActuationType";
        
public const String ImportEventsJournalFileFinished = @"ImportEventsJournalFileFinished";
        
public const String DestinationTypeDesc_Std_ExcelFile = @"DestinationTypeDesc_Std_ExcelFile";
        
public const String DestinationTypeDesc_Std_ExcelFile_Extended = @"DestinationTypeDesc_Std_ExcelFile_Extended";
        
public const String DestinationTypeDesc_Std_CsvFile = @"DestinationTypeDesc_Std_CsvFile";
        
public const String ParamDesc_Converter = @"ParamDesc_Converter";
        
public const String SearchBy_PcObjectAll = @"SearchBy_PcObjectAll";
        
public const String ParamDesc_Children = @"ParamDesc_Children";
        
public const String ParamDesc_Query = @"ParamDesc_Query";
        
public const String ParamDesc_QueryType = @"ParamDesc_QueryType";
        
public const String ParamDesc_TrendSources = @"ParamDesc_TrendSources";
        
public const String ParamDesc_EventTypeTitle = @"ParamDesc_EventTypeTitle";
        
public const String ParamDesc_EventTypeDesc = @"ParamDesc_EventTypeDesc";
        
public const String ParamDesc_EventTitle = @"ParamDesc_EventTitle";
        
public const String ParamDesc_EventDesc = @"ParamDesc_EventDesc";
        
public const String CriterionDesc_TagName = @"CriterionDesc_TagName";
        
public const String CriterionDesc_Event = @"CriterionDesc_Event";
        
public const String Operator_Equals = @"Operator_Equals";
        
public const String Operator_NotEquals = @"Operator_NotEquals";
        
public const String Operator_LessThanOrEquals = @"Operator_LessThanOrEquals";
        
public const String Operator_GreaterThanOrEquals = @"Operator_GreaterThanOrEquals";
        
public const String Operator_LessThan = @"Operator_LessThan";
        
public const String Operator_GreaterThan = @"Operator_GreaterThan";
        
public const String Operator_Contains = @"Operator_Contains";
        
public const String Operator_NotContains = @"Operator_NotContains";
        
public const String Operator_StartsWith = @"Operator_StartsWith";
        
public const String Operator_NotStartsWith = @"Operator_NotStartsWith";
        
public const String Operator_EndsWith = @"Operator_EndsWith";
        
public const String Operator_NotEndsWith = @"Operator_NotEndsWith";
        
public const String Operator_IsEmpty = @"Operator_IsEmpty";
        
public const String Operator_NotIsEmpty = @"Operator_NotIsEmpty";
        
public const String OperatorOption_CaseSensitive = @"OperatorOption_CaseSensitive";
        
public const String CriterionDesc_Params = @"CriterionDesc_Params";
        
public const String ParamDesc_CeMatrixTemplate = @"ParamDesc_CeMatrixTemplate";
        
public const String ParamDesc_BaseActuatorSource = @"ParamDesc_BaseActuatorSource";
        
public const String ParamDesc_SafetyControllerSource = @"ParamDesc_SafetyControllerSource";
        
public const String CriterionDesc_JournalParams = @"CriterionDesc_JournalParams";
        
public const String CriterionDesc_EventParams = @"CriterionDesc_EventParams";
        
public const String CriterionDesc_Severity = @"CriterionDesc_Severity";
        
public const String CriterionDesc_Succeeded = @"CriterionDesc_Succeeded";
        
public const String EncryptAppsettingsSuccess = @"EncryptAppsettingsSuccess";
        
public const String DecryptAppsettingsSuccess = @"DecryptAppsettingsSuccess";
        
public const String SetPostgreCryptoPasswordSuccess = @"SetPostgreCryptoPasswordSuccess";
        
public const String LegendParam = @"LegendParam";
        
public const String ParamDesc_BaseActuatorTemplate = @"ParamDesc_BaseActuatorTemplate";
        
public const String ParamDesc_LegendSource = @"ParamDesc_LegendSource";
        
public const String No = @"No";
        
public const String Yes = @"Yes";
        
public const String ParamDesc_CanBeCause = @"ParamDesc_CanBeCause";
        
public const String ParamDesc_CanBeEffect = @"ParamDesc_CanBeEffect";
        
public const String ParamDesc_TagActuator = @"ParamDesc_TagActuator";
        
public const String Objects_ContentType = @"Objects_ContentType";
        
public const String UnitEvents = @"UnitEvents";
        
public const String Done = @"Done";
        
public const String SetCurrentProjectVersion_JobTitle = @"SetCurrentProjectVersion_JobTitle";
        
public const String Error = @"Error";
        
public const String Units = @"Units";
        
public const String DbFiles = @"DbFiles";
        
public const String ParamDescs = @"ParamDescs";
        
public const String ProjectVersionTypes = @"ProjectVersionTypes";
        
public const String PcObjectEventTypes = @"PcObjectEventTypes";
        
public const String SetCurrentProjectVersion_EventName = @"SetCurrentProjectVersion_EventName";
        
public const String SetCurrentProjectVersion_EventDesc = @"SetCurrentProjectVersion_EventDesc";
        
public const String ParamDesc_SafetyIndexK = @"ParamDesc_SafetyIndexK";
        
public const String ParamDesc_TrendDeadband = @"ParamDesc_TrendDeadband";
        
public const String DestinationTypeDesc_ExportMonitoringEventsReport_HumanReadable_ExcelFile = @"DestinationTypeDesc_ExportMonitoringEventsReport_HumanReadable_ExcelFile";
        
public const String Total = @"Total";
        
public const String DestinationTypeDesc_ExportMonitoringWidgetsReport_HumanReadable_ExcelFile = @"DestinationTypeDesc_ExportMonitoringWidgetsReport_HumanReadable_ExcelFile";
        
public const String DestinationTypeDesc_ExportMonitoringEventsReport_HumanReadable_ExcelFile_Details = @"DestinationTypeDesc_ExportMonitoringEventsReport_HumanReadable_ExcelFile_Details";
        
public const String DestinationTypeDesc_ExportMonitoringWidgetsReport_HumanReadable_ExcelFile_Details = @"DestinationTypeDesc_ExportMonitoringWidgetsReport_HumanReadable_ExcelFile_Details";
        
public const String DestinationTypeDesc_Std_File = @"DestinationTypeDesc_Std_File";
        
public const String SourceTypeDesc_Std_File = @"SourceTypeDesc_Std_File";
        
public const String DestinationTypeDesc_StdJsonExportFileType = @"DestinationTypeDesc_StdJsonExportFileType";
        
public const String DestinationTypeDesc_Std_File_Details = @"DestinationTypeDesc_Std_File_Details";
        
public const String DestinationTypeDesc_Std_ExcelFile_Details = @"DestinationTypeDesc_Std_ExcelFile_Details";
        
public const String DestinationTypeDesc_Std_ExcelFile_Extended_Details = @"DestinationTypeDesc_Std_ExcelFile_Extended_Details";
        
public const String DestinationTypeDesc_HumanReadable_ExcelFile_Details = @"DestinationTypeDesc_HumanReadable_ExcelFile_Details";
        
public const String SourceTypeDesc_Std_File_Details = @"SourceTypeDesc_Std_File_Details";
        
public const String SourceTypeDesc_PcLicFileType = @"SourceTypeDesc_PcLicFileType";
        
public const String SourceTypeDesc_PcLicFileType_Details = @"SourceTypeDesc_PcLicFileType_Details";
        
public const String SearchBy_IdentifierTitleDesc = @"SearchBy_IdentifierTitleDesc";
        
public const String PcObjectEvents = @"PcObjectEvents";
        
public const String InformationSecurityEvents = @"InformationSecurityEvents";
        
public const String Error_SeeApplicationLogFilesForDetails = @"Error_SeeApplicationLogFilesForDetails";
        
public const String Error_FileNotFound = @"Error_FileNotFound";
        
public const String Scope_KeyName = @"Scope_KeyName";
        
public const String Error_KeyRequiredIsMissing = @"Error_KeyRequiredIsMissing";
        
public const String Error_KeyUnknownValue = @"Error_KeyUnknownValue";
        
public const String Error_KeyDuplicateValue = @"Error_KeyDuplicateValue";
        
public const String Scope_FilePartName = @"Scope_FilePartName";
        
public const String Error_ExportReport = @"Error_ExportReport";
        
public const String Error_SendEMail = @"Error_SendEMail";
        
public const String ImportFilePreview_EventDesc = @"ImportFilePreview_EventDesc";
        
public const String ImportFilePreview_EventName = @"ImportFilePreview_EventName";
        
public const String EMails_EventId = @"EMails_EventId";
        
    } 
}