/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// AnnotationsRequest
    /// </summary>    
    public class AnnotationsRequest
    {        
        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public AnnotationsRequestRange? Range { get; set; }

        /// <summary>
        /// Gets or Sets RangeRaw
        /// </summary>
        [JsonPropertyName("rangeRaw")]
        public RawTimeFrame? RangeRaw { get; set; }

        /// <summary>
        /// Gets or Sets Annotation
        /// </summary>
        [JsonPropertyName("annotation")]
        public AnnotationsRequestAnnotation? Annotation { get; set; }

        /// <summary>
        /// Gets or Sets Variables
        /// </summary>
        [JsonPropertyName("variables")]
        public object? Variables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnnotationsRequest {\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  RangeRaw: ").Append(RangeRaw).Append("\n");
            sb.Append("  Annotation: ").Append(Annotation).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
