/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// AnnotationsRequestAnnotation
    /// </summary>    
    public class AnnotationsRequestAnnotation
    {        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>deploy</example>
        [JsonPropertyName("name")]
        public string Name { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Datasource
        /// </summary>
        /// <example>JSON datasource</example>
        [JsonPropertyName("datasource")]
        public string Datasource { get; set; } = @"";

        /// <summary>
        /// Gets or Sets IconColor
        /// </summary>
        /// <example>rgba(255, 96, 96, 1)</example>
        [JsonPropertyName("iconColor")]
        public string IconColor { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Enable
        /// </summary>
        [JsonPropertyName("enable")]
        public bool Enable { get; set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        /// <example>#deploy</example>
        [JsonPropertyName("query")]
        public string Query { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnnotationsRequestAnnotation {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Datasource: ").Append(Datasource).Append("\n");
            sb.Append("  IconColor: ").Append(IconColor).Append("\n");
            sb.Append("  Enable: ").Append(Enable).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
