/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// Annotations200ResponseInner
    /// </summary>    
    public class Annotations200ResponseInner
    {
        /// <summary>
        /// Text for the annotation. (required)
        /// </summary>
        /// <example>text shown in body</example>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; } = @"";

        /// <summary>
        /// The title for the annotation tooltip. (optional)
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; } = @"";

        /// <summary>
        /// Whether is region. (optional) (http://docs.grafana.org/reference/annotations/#adding-regions-events)
        /// </summary>
        [DataMember(Name = "isRegion", EmitDefaultValue = true)]
        public bool IsRegion { get; set; }

        /// <summary>
        /// Time since UNIX Epoch in milliseconds. (required)
        /// </summary>
        [DataMember(Name = "time", IsRequired = true, EmitDefaultValue = true)]
        public string Time { get; set; } = @"";

        /// <summary>
        /// Time since UNIX Epoch in milliseconds (required if `isRegion` is true )
        /// </summary>
        /// <value>required if isRegion is true</value>
        [DataMember(Name = "timeEnd", EmitDefaultValue = false)]
        public string TimeEnd { get; set; } = @"";

        /// <summary>
        /// Tags for the annotation. (optional)
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string>? Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Annotations200ResponseInner {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  IsRegion: ").Append(IsRegion).Append("\n");
            sb.Append("  TimeEnd: ").Append(TimeEnd).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }
    }
}
