/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// ListMetrics200ResponseInner
    /// </summary>
    [JsonConverter(typeof(ListMetrics200ResponseInnerJsonConverter))]
    [DataContract(Name = "api_endpoints_list_metrics_200_response_inner")]
    public partial class ListMetrics200ResponseInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListMetrics200ResponseInner" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public ListMetrics200ResponseInner(string? actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListMetrics200ResponseInner" /> class
        /// with the <see cref="ListMetrics200ResponseInnerOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ListMetrics200ResponseInnerOneOf.</param>
        public ListMetrics200ResponseInner(ListMetrics200ResponseInnerOneOf? actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance = null!;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ListMetrics200ResponseInnerOneOf))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ListMetrics200ResponseInnerOneOf, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ListMetrics200ResponseInnerOneOf`. If the actual instance is not `ListMetrics200ResponseInnerOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ListMetrics200ResponseInnerOneOf</returns>
        public ListMetrics200ResponseInnerOneOf GetListMetrics200ResponseInnerOneOf()
        {
            return (ListMetrics200ResponseInnerOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListMetrics200ResponseInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ListMetrics200ResponseInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ListMetrics200ResponseInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ListMetrics200ResponseInner</returns>
        public static ListMetrics200ResponseInner? FromJson(string jsonString)
        {
            ListMetrics200ResponseInner? newListMetrics200ResponseInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newListMetrics200ResponseInner;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ListMetrics200ResponseInnerOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newListMetrics200ResponseInner = new ListMetrics200ResponseInner(JsonConvert.DeserializeObject<ListMetrics200ResponseInnerOneOf>(jsonString, ListMetrics200ResponseInner.SerializerSettings));
                }
                else
                {
                    newListMetrics200ResponseInner = new ListMetrics200ResponseInner(JsonConvert.DeserializeObject<ListMetrics200ResponseInnerOneOf>(jsonString, ListMetrics200ResponseInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ListMetrics200ResponseInnerOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ListMetrics200ResponseInnerOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newListMetrics200ResponseInner = new ListMetrics200ResponseInner(JsonConvert.DeserializeObject<string>(jsonString, ListMetrics200ResponseInner.SerializerSettings));
                }
                else
                {
                    newListMetrics200ResponseInner = new ListMetrics200ResponseInner(JsonConvert.DeserializeObject<string>(jsonString, ListMetrics200ResponseInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newListMetrics200ResponseInner;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ListMetrics200ResponseInner
    /// </summary>
    public class ListMetrics200ResponseInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ListMetrics200ResponseInner).GetMethod("ToJson")!.Invoke(value, null)!));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.String: 
                    return new ListMetrics200ResponseInner(Convert.ToString(reader.Value));
                case JsonToken.StartObject:
                    return ListMetrics200ResponseInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ListMetrics200ResponseInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
