/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// table case
    /// </summary>
    [DataContract(Name = "api_endpoints_query_200_response_inner_anyOf_1")]
    public partial class Query200ResponseInnerAnyOf1 : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Table for value: table
            /// </summary>
            [EnumMember(Value = "table")]
            Table = 1
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Query200ResponseInnerAnyOf1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf1" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="columns">columns (required).</param>
        /// <param name="rows">rows (required).</param>
        public Query200ResponseInnerAnyOf1(TypeEnum type = default(TypeEnum), List<Query200ResponseInnerAnyOf1ColumnsInner>? columns = default(List<Query200ResponseInnerAnyOf1ColumnsInner>), List<object[]>? rows = default(List<object[]>))
        {
            this.Type = type;
            // to ensure "columns" is required (not null)
            if (columns == null)
            {
                throw new ArgumentNullException("columns is a required property for Query200ResponseInnerAnyOf1 and cannot be null");
            }
            this.Columns = columns;
            // to ensure "rows" is required (not null)
            if (rows == null)
            {
                throw new ArgumentNullException("rows is a required property for Query200ResponseInnerAnyOf1 and cannot be null");
            }
            this.Rows = rows;
        }

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [DataMember(Name = "columns", IsRequired = true, EmitDefaultValue = true)]
        public List<Query200ResponseInnerAnyOf1ColumnsInner>? Columns { get; set; }

        /// <summary>
        /// Gets or Sets Rows
        /// </summary>
        /// <example>[[1557385723416,&quot;SE&quot;,123],[1557385731634,&quot;SE&quot;,456]]</example>
        [DataMember(Name = "rows", IsRequired = true, EmitDefaultValue = true)]
        public List<object[]>? Rows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Query200ResponseInnerAnyOf1 {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
