/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// timeseries case
    /// </summary>
    [DataContract(Name = "api_endpoints_query_200_response_inner_anyOf")]
    public partial class Query200ResponseInnerAnyOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Query200ResponseInnerAnyOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf" /> class.
        /// </summary>
        /// <param name="target">target (required).</param>
        /// <param name="datapoints">datapoints (required).</param>
        public Query200ResponseInnerAnyOf(string target = @"", List<List<decimal>>? datapoints = default(List<List<decimal>>))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for Query200ResponseInnerAnyOf and cannot be null");
            }
            this.Target = target;
            // to ensure "datapoints" is required (not null)
            if (datapoints == null)
            {
                throw new ArgumentNullException("datapoints is a required property for Query200ResponseInnerAnyOf and cannot be null");
            }
            this.Datapoints = datapoints;
        }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        /// <example>upper_25</example>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Datapoints
        /// </summary>
        /// <example>[[2.5,1557385723416],[3.5,1557385731634]]</example>
        [DataMember(Name = "datapoints", IsRequired = true, EmitDefaultValue = true)]
        public List<List<decimal>>? Datapoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Query200ResponseInnerAnyOf {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Datapoints: ").Append(Datapoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
