/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// Query200ResponseInnerAnyOf1ColumnsInner
    /// </summary>
    [DataContract(Name = "api_endpoints_query_200_response_inner_anyOf_1_columns_inner")]
    public partial class Query200ResponseInnerAnyOf1ColumnsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf1ColumnsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Query200ResponseInnerAnyOf1ColumnsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInnerAnyOf1ColumnsInner" /> class.
        /// </summary>
        /// <param name="text">text (required).</param>
        /// <param name="type">type.</param>
        public Query200ResponseInnerAnyOf1ColumnsInner(string text = @"", string type = @"")
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for Query200ResponseInnerAnyOf1ColumnsInner and cannot be null");
            }
            this.Text = text;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Query200ResponseInnerAnyOf1ColumnsInner {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
