/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// QueryRequest
    /// </summary>    
    public class QueryRequest
    {        
        [JsonPropertyName("app")]
        public string App { get; set; } = @"";

        [JsonPropertyName("requestId")]
        public string RequestId { get; set; } = @"";

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; } = @"";

        /// <summary>
        /// Gets or Sets PanelId
        /// </summary>
        [JsonPropertyName("panelId")]
        public object? PanelId { get; set; }

        [JsonPropertyName("dashboardId")]
        public object? DashboardId { get; set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public QueryRequestRange? Range { get; set; }

        /// <summary>
        /// Gets or Sets RangeRaw
        /// </summary>
        [JsonPropertyName("rangeRaw")]
        public RawTimeFrame? RangeRaw { get; set; }

        [JsonPropertyName("timeInfo")]
        public string TimeInfo { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Interval
        /// </summary>
        /// <example>30s</example>
        [JsonPropertyName("interval")]
        public string Interval { get; set; } = @"";

        /// <summary>
        /// Gets or Sets IntervalMs
        /// </summary>
        /// <example>5500</example>
        [JsonPropertyName("intervalMs")]
        public decimal IntervalMs { get; set; }

        /// <summary>
        /// Gets or Sets MaxDataPoints
        /// </summary>
        /// <example>50</example>
        [JsonPropertyName("maxDataPoints")]
        public decimal MaxDataPoints { get; set; }

        /// <summary>
        /// Gets or Sets Targets
        /// </summary>
        [JsonPropertyName("targets")]
        public List<QueryRequestTargetsInner>? Targets { get; set; }

        /// <summary>
        /// Gets or Sets ScopedVars
        /// </summary>
        /// <example>{&quot;__interval&quot;:{&quot;text&quot;:&quot;1s&quot;,&quot;value&quot;:&quot;1s&quot;},&quot;__interval_ms&quot;:{&quot;text&quot;:1000,&quot;value&quot;:1000}}</example>
        [JsonPropertyName("scopedVars")]
        public object? ScopedVars { get; set; }

        [JsonPropertyName("startTime")]
        public object? StartTime { get; set; }

        /// <summary>
        /// Gets or Sets AdhocFilters
        /// </summary>
        [JsonPropertyName("adhocFilters")]
        public List<QueryRequestAdhocFiltersInner>? AdhocFilters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRequest {\n");
            sb.Append("  PanelId: ").Append(PanelId).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  RangeRaw: ").Append(RangeRaw).Append("\n");
            sb.Append("  Interval: ").Append(Interval).Append("\n");
            sb.Append("  IntervalMs: ").Append(IntervalMs).Append("\n");
            sb.Append("  MaxDataPoints: ").Append(MaxDataPoints).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  ScopedVars: ").Append(ScopedVars).Append("\n");
            sb.Append("  AdhocFilters: ").Append(AdhocFilters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
