/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// QueryRequestTargetsInner
    /// </summary>    
    public class QueryRequestTargetsInner
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(JsonStringEnumConverter<TypeEnum>))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Timeseries for value: timeseries
            /// </summary>
            [JsonPropertyName("timeseries")]
            Timeseries = 1,

            /// <summary>
            /// Enum Table for value: table
            /// </summary>
            [JsonPropertyName("table")]
            Table = 2
        }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        /// <example>upper_25</example>
        [JsonPropertyName("target")]
        public decimal Target { get; set; }

        /// <summary>
        /// Gets or Sets RefId
        /// </summary>
        [JsonPropertyName("refId")]
        public string RefId { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// arbitrary \&quot;additional data\&quot; the user can pass in
        /// </summary>
        /// <value>arbitrary \&quot;additional data\&quot; the user can pass in</value>
        [JsonPropertyName("data")]
        public object? Data { get; set; }

        [JsonPropertyName("datasource")]
        public string Datasource { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRequestTargetsInner {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  RefId: ").Append(RefId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }        
    }

}
