/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// Query200ResponseInner
    /// </summary>
    [JsonConverter(typeof(Query200ResponseInnerJsonConverter))]
    [DataContract(Name = "api_endpoints_query_200_response_inner")]
    public partial class Query200ResponseInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInner" /> class
        /// with the <see cref="Query200ResponseInnerAnyOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Query200ResponseInnerAnyOf.</param>
        public Query200ResponseInner(Query200ResponseInnerAnyOf? actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Query200ResponseInner" /> class
        /// with the <see cref="Query200ResponseInnerAnyOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Query200ResponseInnerAnyOf1.</param>
        public Query200ResponseInner(Query200ResponseInnerAnyOf1? actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance = null!;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(Query200ResponseInnerAnyOf))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Query200ResponseInnerAnyOf1))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: Query200ResponseInnerAnyOf, Query200ResponseInnerAnyOf1");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `Query200ResponseInnerAnyOf`. If the actual instance is not `Query200ResponseInnerAnyOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Query200ResponseInnerAnyOf</returns>
        public Query200ResponseInnerAnyOf GetQuery200ResponseInnerAnyOf()
        {
            return (Query200ResponseInnerAnyOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Query200ResponseInnerAnyOf1`. If the actual instance is not `Query200ResponseInnerAnyOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Query200ResponseInnerAnyOf1</returns>
        public Query200ResponseInnerAnyOf1 GetQuery200ResponseInnerAnyOf1()
        {
            return (Query200ResponseInnerAnyOf1)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Query200ResponseInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, Query200ResponseInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Query200ResponseInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Query200ResponseInner</returns>
        public static Query200ResponseInner? FromJson(string jsonString)
        {
            Query200ResponseInner? newQuery200ResponseInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newQuery200ResponseInner;
            }

            try
            {
                newQuery200ResponseInner = new Query200ResponseInner(JsonConvert.DeserializeObject<Query200ResponseInnerAnyOf>(jsonString, Query200ResponseInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newQuery200ResponseInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Query200ResponseInnerAnyOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newQuery200ResponseInner = new Query200ResponseInner(JsonConvert.DeserializeObject<Query200ResponseInnerAnyOf1>(jsonString, Query200ResponseInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newQuery200ResponseInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Query200ResponseInnerAnyOf1: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Query200ResponseInner
    /// </summary>
    public class Query200ResponseInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Query200ResponseInner).GetMethod("ToJson")!.Invoke(value, null)!));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return Query200ResponseInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Query200ResponseInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
