/*
 * simPod JSON Datasource API
 *
 * API definition for the Grafana plugin simpod json datasource https://github.com/simPod/grafana-json-datasource
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Simcode.PazCheck.CentralServer.Presentation.Grafana.Serialization
{
    /// <summary>
    /// QueryRequestAdhocFiltersInner
    /// </summary>    
    public class QueryRequestAdhocFiltersInner
    {        
        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        /// <example>City</example>
        [JsonPropertyName("key")]
        public string Key { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        /// <example>&#x3D;</example>
        [JsonPropertyName("operator")]
        public string Operator { get; set; } = @"";

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        /// <example>Berlin</example>
        [JsonPropertyName("value")]
        public string Value { get; set; } = @"";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRequestAdhocFiltersInner {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
